"""init schema

Revision ID: 1c56c646669e
Revises: 
Create Date: 2025-12-30 11:32:23.588552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c56c646669e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/Riga', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('agent_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_recommendations_user_id'), 'agent_recommendations', ['user_id'], unique=False)
    op.create_table('taste_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), server_default='', nullable=False),
    sa.Column('weights_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('avoids_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('watched_films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('your_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('your_review', sa.Text(), nullable=True),
    sa.Column('watched_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='letterboxd', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('letterboxd','agent','manual')", name='chk_watched_source'),
    sa.CheckConstraint('your_rating IS NULL OR (your_rating >= 0 AND your_rating <= 5)', name='chk_watched_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_films_tmdb_id'), 'watched_films', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_watched_films_user_id'), 'watched_films', ['user_id'], unique=False)
    op.create_index('ix_watched_user_tmdb', 'watched_films', ['user_id', 'tmdb_id'], unique=False)
    op.create_table('agent_recommendation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=32), server_default='safe', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='suggested', nullable=False),
    sa.Column('explanation_shown', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('suggested','watched','skipped')", name='chk_item_status'),
    sa.CheckConstraint("strategy IN ('safe','adjacent','wildcard')", name='chk_item_strategy'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['agent_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_recommendation_items_recommendation_id'), 'agent_recommendation_items', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_agent_recommendation_items_tmdb_id'), 'agent_recommendation_items', ['tmdb_id'], unique=False)
    op.create_index('ix_rec_items_recid_pos', 'agent_recommendation_items', ['recommendation_id', 'position'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_item_id', sa.Integer(), nullable=False),
    sa.Column('your_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('your_review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('your_rating IS NULL OR (your_rating >= 0 AND your_rating <= 5)', name='chk_feedback_rating_range'),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['agent_recommendation_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_recommendation_item_id'), 'feedback', ['recommendation_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_recommendation_item_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_rec_items_recid_pos', table_name='agent_recommendation_items')
    op.drop_index(op.f('ix_agent_recommendation_items_tmdb_id'), table_name='agent_recommendation_items')
    op.drop_index(op.f('ix_agent_recommendation_items_recommendation_id'), table_name='agent_recommendation_items')
    op.drop_table('agent_recommendation_items')
    op.drop_index('ix_watched_user_tmdb', table_name='watched_films')
    op.drop_index(op.f('ix_watched_films_user_id'), table_name='watched_films')
    op.drop_index(op.f('ix_watched_films_tmdb_id'), table_name='watched_films')
    op.drop_table('watched_films')
    op.drop_table('taste_profile')
    op.drop_index(op.f('ix_agent_recommendations_user_id'), table_name='agent_recommendations')
    op.drop_table('agent_recommendations')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
