"""add command_rate_limits

Revision ID: 5e0353c68b30
Revises: df44363c6004
Create Date: 2025-12-31 00:40:32.138823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0353c68b30'
down_revision: Union[str, Sequence[str], None] = 'df44363c6004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_rate_limits',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'command')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_rate_limits')
    # ### end Alembic commands ###
