"""add tmdb cache tables

Revision ID: ac77d153fa51
Revises: 1c56c646669e
Create Date: 2025-12-30 11:37:04.152512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac77d153fa51'
down_revision: Union[str, Sequence[str], None] = '1c56c646669e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmdb_movie_details_cache',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_index('ix_tmdb_details_expires', 'tmdb_movie_details_cache', ['expires_at'], unique=False)
    op.create_table('tmdb_movie_keywords_cache',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_index('ix_tmdb_keywords_expires', 'tmdb_movie_keywords_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tmdb_keywords_expires', table_name='tmdb_movie_keywords_cache')
    op.drop_table('tmdb_movie_keywords_cache')
    op.drop_index('ix_tmdb_details_expires', table_name='tmdb_movie_details_cache')
    op.drop_table('tmdb_movie_details_cache')
    # ### end Alembic commands ###
